apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argocd-image-updater
    repo: https://argoproj.github.io/argo-helm
    version: 0.8.1
    releaseName: argocd-image-updater
    namespace: argocd
    includeCRDs: true
    valuesFile: values.yaml
