apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/applications.yaml
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.5.3

patchesJson6902:
  - path: overlays/deploy-command.yaml
    target:
      group: apps
      kind: Deployment
      name: argocd-server
      version: v1

namespace: argocd
