apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: ssm
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
          jwt:
            serviceAccountRef:
              name: external-secrets
              namespace: external-secrets
