apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
spec:
  project: default
  source:
    chart: argocd-image-updater
    repoURL: "https://argoproj.github.io/argo-helm"
    targetRevision: v0.12.0
    helm:
      valueFiles: values-override.yaml
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
