apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  project: default
  source:
    path: external-secrets
    repoURL: "https://github.com/s0rl0v/weather-k8s-deployments.git"
    targetRevision: main
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
