apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: default
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.4.0
    helm:
      values: |
        controller:
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
  ignoreDifferences:
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/metrics
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
