apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-backend
spec:
  project: default
  source:
    repoURL: "https://github.com/s0rl0v/weather-k8s-deployments.git"
    path: weather-backend
    targetRevision: main
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
