apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master

helmCharts:
  - name: aws-load-balancer-controller
    repo: https://aws.github.io/eks-charts
    version: 1.4.6
    releaseName: aws-load-balancer-controller
    namespace: kube-system
    valuesFile: values.yaml
