replicaCount: 1

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::092592202483:role/AmazonEKSLoadBalancerControllerRole"
  name: "aws-load-balancer-controller"

nodeSelector:
  node-type: general

# The name of the Kubernetes cluster. A non-empty value is required
clusterName: "sorlov-sandbox"
