apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "weather-backend.fullname" . }}-metrics
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "weather-backend.fullname" . }}
  endpoints:
  - port: metrics
  namespaceSelector:
    any: true
