apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weather-backend-metrics
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: weather-backend
  endpoints:
  - targetPort: 8080
    path: /metrics
  namespaceSelector:
    any: true
