resources:
- ./resources/argocd-metrics-servicemonitor.yaml
- ./resources/argocd-server-metrics-servicemonitor.yaml
- ./resources/argocd-repo-server-metrics-servicemonitor.yaml
- ./resources/argocd-notifications-controller-metrics-servicemonitor.yaml
- ./resources/grafana-ingress.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 42.2.1
    releaseName: kube-prometheus-stack
    namespace: monitoring
    includeCRDs: true

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"

configMapGenerator:
- name: argocd-dashboard-cm
  files:
    - dashboard.json

patchesJson6902:
- target:
    name: kube-prometheus-stack-grafana
    namespace: monitoring
    group:
    version: v1
    kind: Secret
  path: overlays/prometheus-operator-grafana-secret.yaml

patchesStrategicMerge:
- overlays/prometheus-operator-grafana-cm.yaml
