apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../charts

helmCharts:
- releaseName: weather-backend
  namespace: production
  name: weather-backend
  version: 0.0.1
  valuesFile: values.yaml
