apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-backend
  namespace: development
spec:
  project: default
  source:
    path: chart
    repoURL: "https://github.com/s0rl0v/weather-app.git"
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: development
