apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: { { include "weather-backend.fullname" . } }
spec:
  backendType: systemManager
  data:
    - key: { { include "ssm_secret_path" . } }
      name: apikey
